version: "3"
services:
  db:
    image: postgres:11.1-alpine
    env_file: docker/.dockerenv
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/backup:/backup
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2.2-alpine
    restart: always
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"
  app:
    build: .
    image: 'app'
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - migrate
    volumes:
      - ./app:/app
      - ./media:/app/media/
  migrate:
    image: app:latest
    command: python manage.py migrate
    env_file:
      - .env
    depends_on:
      - db

