# Generated by Django 4.1.3 on 2022-11-20 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Date')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Amount')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Date')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='dictionary.dictionary', verbose_name='Dictionary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='dictionary',
            name='language_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dicts_to', to='dictionary.language', verbose_name='Language from'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='language_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dicts_from', to='dictionary.language', verbose_name='Language to'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dicts', to='dictionary.level', verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dicts', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='dicts', to='dictionary.tag', verbose_name='Tags'),
        ),
    ]
