# Generated by Django 4.1.3 on 2022-11-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='icon',
            field=models.ImageField(null=True, upload_to='icons'),
        ),
    ]
