# Generated by Django 4.1.3 on 2022-11-21 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0002_language_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='pinned',
            field=models.ManyToManyField(related_name='dicts_pinned', to=settings.AUTH_USER_MODEL, verbose_name='Pinned'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'dictionary')},
        ),
    ]
