# Generated by Django 4.1.3 on 2022-11-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
