# Generated by Django 4.1.3 on 2022-11-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_dictionary_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='example_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Example 1'),
        ),
        migrations.AlterField(
            model_name='words',
            name='example_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Example 2'),
        ),
        migrations.AlterField(
            model_name='words',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
