# Generated by Django 4.1.3 on 2022-11-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_words_example_1_alter_words_example_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='example_1',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Example 1'),
        ),
        migrations.AlterField(
            model_name='words',
            name='example_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Example 2'),
        ),
        migrations.AlterField(
            model_name='words',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='words/'),
        ),
        migrations.AlterField(
            model_name='words',
            name='word_from',
            field=models.CharField(default='', max_length=50, verbose_name='Word from'),
        ),
        migrations.AlterField(
            model_name='words',
            name='word_to',
            field=models.CharField(default='', max_length=50, verbose_name='Word from'),
        ),
    ]
