# Generated by Django 4.1.3 on 2022-11-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_alter_words_example_1_alter_words_example_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='session_count',
            field=models.ImageField(default=0, upload_to='', verbose_name='Session count'),
        ),
    ]
