# Generated by Django 4.1.3 on 2022-11-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_words_session_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='session_count',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='session_count',
            field=models.ImageField(default=0, upload_to='', verbose_name='Session count'),
        ),
    ]
