# Generated by Django 4.1.3 on 2022-11-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_remove_words_session_count_dictionary_session_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='session_count',
            field=models.BooleanField(default=0, verbose_name='Session count'),
        ),
    ]
