# Generated by Django 4.1.3 on 2022-11-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_alter_dictionary_session_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
            ],
        ),
        migrations.AddField(
            model_name='dictionary',
            name='learning_mods',
            field=models.ManyToManyField(related_name='dicts', to='dictionary.learningmode', verbose_name='Learning mods'),
        ),
    ]
