# Generated by Django 4.1.3 on 2022-12-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_words_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='prononsiation',
            field=models.FileField(blank=True, null=True, upload_to='words_prononsiation/'),
        ),
    ]
